# 部署静态doc网站
name: Deploy Storybook

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  whether-deploy:
    runs-on: ubuntu-latest
    outputs:
      should-deploy: ${{ steps.check-commit.outputs.should-deploy }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check commit messages
        id: check-commit
        run: |
          #!/bin/bash
          set -e

          should_deploy="false"
          commit_message=$(git log -1 --pretty=%B)

          # 检查提交信息中是否包含 [release x.y.z]
          if [[ $commit_message =~ \[release[[:space:]]([0-9]+\.[0-9]+\.[0-9]+)\] ]]; then
            should_deploy="true"
          fi

          echo "should-deploy=$should_deploy" >> $GITHUB_OUTPUT

  build-and-deploy:
    needs: whether-deploy
    if: needs.whether-deploy.outputs.should-deploy == 'true'
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.11.0
          run_install: false

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build Storybook
        run: pnpm run build-storybook

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: storybook-static

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
